### PR TITLE
Add scramble xormask

### LINKED ISSUE #38: XOR Patch Feature
# Summary
One useful feature that can be added to OpenVPN is the [scramble xor patch](https://tunnelblick.net/cOpenvpn_xorpatch.html) (<a href="https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party/sources/openvpn/openvpn-2.4.6/patches">github</a>). It XORs all bytes sent by openvpn, evading firewalls. It would be a great addition to passepartout that would make it stand out from the official iOS OpenVPN app, and it should be relatively simple to implement.

[Original reddit post](https://www.reddit.com/r/passepartout/comments/9pnxsv/openvpn_xor_patch/)

### PR DESCRIPTION
**Pull request by keeshux**
Rebase of #121 

Fixes #38

cc @XMB5

### CODE REVIEW

**Comment by HosseyNJF** [comment]
Why this isn't being merged?

**Comment by hybtoy** [comment]
> Why this isn't being merged?
+1
Hopefully, will be merged soon.

**Comment by keeshux** [comment]
@XMB5 I notice your additions in the copyright header. While I have no issue with crediting one's work (goes without saying), it's impossible to track authorship on a line by line basis. In fact the header is more of a Xcode placeholder.

Would you be okay with being credited in a different manner? E.g. in README, LICENSE or wherever else you're okay with. As is, I'm not sure about merging this as I don't want this to cause trouble in the future.

Feel free to contact me privately on me@davidederosa.com for more insight.

**Comment by keeshux** [comment]
Other than that, the "official" Tunnelblick patch takes a string as input. Do you confirm this PR only supports a single byte XOR mask?

**Comment by XMB5** [comment]
@keeshux I'm fine with being credited in any way, for example in the README, LICENSE, at the top of the file, or even only in `git log` (i.e. not written down in any file, only in git metadata).

And yes, this patch only supports a single byte mask--see [ConfigurationParser.swift line 470](https://github.com/passepartoutvpn/tunnelkit/pull/170/commits/0eeec1f1b1af7ae7be5796f557b50ca48055164e#diff-a707d5b235820f006a69617879eb0985fd233175978baad4372c1f9fb8658740R470):
```swift
optXorMask = Character($0[1]).asciiValue
```

Although the official patch supports multiple bytes, in practice, people often use only 1 byte because it is sufficient to evade firewalls (for example, ExpressVPN does this, although they use a custom option name instead of `scramble xormask`).

**Comment by keeshux** [comment]
Nice! Please check out last 2 commits.

**Comment by R2D2me** [comment]
@keeshux Am I right that you plan to merge it soon?

**Comment by XMB5** [comment]
@keeshux The new commits look good. My one comment is that maybe we should document this feature somewhere, perhaps in the README? Here's some text we could use:

`--scramble xormask <character>` -- XOR all incoming and outgoing bytes by the ascii value of this character
- Only single-byte masks supported
- See https://tunnelblick.net/cOpenvpn_xorpatch.html for details

**Pull request merged**
