### PR TITLE
Add Complete XOR Patch Functionality

### PR DESCRIPTION
**Pull request by tmthecoder**
This PR adds complete XOR patch functionality (building on the existing single-byte `scramble xormask` statement).

This feature adds the following specifically:
- `scramble xormask [password]`: Same as existing, but with added support for multibyte passwords
- `scramble xorptrpos`: XORs the byte of each packet with its position in the array
- `scramble reverse`: Keeps the first byte but reverses the remaining ('abcde' becomes 'aedcb')
- `scramble obfuscate [password]`: Performs a combination of the three above with the given passphrase on the mask stage. For reading it goes in this order: xormask -> xorptrpos -> reverse -> xorptrpos. Writing is the opposite

All of these implementations are done following [Tunnelblick's XOR patch](https://github.com/clayface/openvpn_xorpatch/blob/master/openvpn_xor.patch) and their small article on it [here](https://tunnelblick.net/cOpenvpn_xorpatch.html) (Header titled "Scramble Option Syntax")

I've found myself needed the full extent of this functionality, specifically the `scramble obfuscate` option with a multu-byte password, hence my decision to write an implementation for it. I believe I've followed the guidelines outlined as well as the code structure already defined. Looking forward to hearing your insight!

### CODE REVIEW

**Comment by tmthecoder** [comment]
Also, please note that this does change the `xorMask` type to a `Data` as opposed to a `UInt8` since we've added support for multibyte values to be used as the `xormask` or `obfuscate` arguments

**Comment by keeshux** [comment]
> @keeshux Just looking here again, should I add in a commit to update the README with the complete XOR functionality?

Hey, yes you can go ahead with that. Sorry that I won't be able to review this until I release Passepartout 2.0

**Review by keeshux — APPROVED** [review]

**Comment by keeshux** [comment]
Okay, time has finally come to look into this.

**Comment by keeshux** [comment]
@tmthecoder sorry for the long delay!

First of all, thanks again for your dedication, this is great work and I'm sincerely glad for your contribution.

I could finally take some time to review this and I refactored your code to fit it better into the library. It's all about simplifying and moving things around, but the purpose and algorithms should be 100% unaffected.

Since I understand you are using all these in your server, please do some stress tests with this updated code of mine. Meanwhile, I'll try to at least add some unit tests of the XOR processing routines, to make sure e.g. that packets are correctly reversible (p1 -> scramble -> p2 -> scramble -> p1).

Cheers

**Comment by tmthecoder** [comment]
@keeshux Sounds good, I'll run some tests on my setups

**Comment by tmthecoder** [comment]
@keeshux Couldn't find any issues in local tests against VPN servers

**Comment by keeshux** [comment]
> @keeshux Couldn't find any issues in local tests against VPN servers

Awesome. Have you also ensured continued operation in UDP/TCP _without_ any XOR option enabled?

**Comment by keeshux** [comment]
Tested myself, and Passepartout beta will be another testbed. Merged!

**Comment by daaku** [comment]
Wondering when this will be in TestFlight / Release?

**Comment by keeshux** [comment]
> Wondering when this will be in TestFlight / Release?

It's in TestFlight versions already.

**Comment by keeshux** [comment]
@tmthecoder your work is now part of Passepartout 2.1.0 on the App Store. Thanks again!

@daaku FYI

**Pull request merged**
